version: '3.3'
services:
  # db:
  #   image: postgres
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  
  calculadora:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: calculadora
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./source:/source
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
      