# Generated by Django 3.1.7 on 2021-03-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculadora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_1', models.IntegerField()),
                ('number_2', models.IntegerField()),
                ('operacao', models.CharField(choices=[('soma', 'Soma'), ('subtracao', 'Subtração'), ('multiplicacao', 'Multiplicação'), ('divisao', 'Divisão')], max_length=13)),
            ],
            options={
                'verbose_name': 'Calculadora',
                'verbose_name_plural': 'Calculadoras',
            },
        ),
    ]
