# Generated by Django 3.1.7 on 2021-03-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcular', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_1', models.IntegerField()),
                ('number_2', models.IntegerField()),
            ],
            options={
                'verbose_name': 'divisão',
            },
        ),
        migrations.CreateModel(
            name='Multiplicacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_1', models.IntegerField()),
                ('number_2', models.IntegerField()),
            ],
            options={
                'verbose_name': 'multiplicação',
            },
        ),
        migrations.CreateModel(
            name='Soma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_1', models.IntegerField()),
                ('number_2', models.IntegerField()),
            ],
            options={
                'verbose_name': 'soma',
            },
        ),
        migrations.CreateModel(
            name='Subtracao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_1', models.IntegerField()),
                ('number_2', models.IntegerField()),
            ],
            options={
                'verbose_name': 'subtração',
            },
        ),
        migrations.AlterModelOptions(
            name='calculadora',
            options={'verbose_name': 'calculo'},
        ),
    ]
